# poetry run black-nb notebooks/baseball/
# poetry run jupyter nbconvert --to notebook  --execute notebooks/baseball/main.ipynb --inplace
name: Test
on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python: ["3.7", "3.8", "3.9"]
      fail-fast: false
    name: Test on ${{ matrix.os }} with Python ${{ matrix.python }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          architecture: x64
          python-version: ${{ matrix.python }}

      - name: Install Poetry
        run: pip install poetry

      - name: Install Python dependencies
        run: poetry install

      - name: Run Black
        env:
          JDK4PY_BUILD_PLATFORM: ${{ matrix.os }}
        shell: bash
        run: poetry run black-nb --check notebooks/

      - name: Test notebooks execution
        env:
          JDK4PY_BUILD_PLATFORM: ${{ matrix.os }}
        shell: bash
        run: |
          mkdir temp
          poetry run python .github/workflows/test_notebooks.py
